= Kamura: Groovy builders and reader for day-to-day data formats
John Hurst <john.b.hurst@gmail.com>
v0.0.1, 2016-06-04

Kamura is a project containing Groovy builders and readers for creating and processing
popular types of data that are common in day-to-day work.

"Kamura" is the Māori word for carpenter.

Kamura is organised into very small modules, so that you do not need to add dependencies for what you don't need.

Kamura modules are grouped into two basic types.

* xxx-builder modules provide Groovy http://groovy-lang.org/dsls.html[builder DLSs] to construct objects using clean, readable code.
* xxx-reader modules provide convenient wrappers for reading objects using Groovy, e.g. providing closure support.

In most cases, Kamura builders wrap existing Java libraries that support the underlying data types.

So for example, kamura-itext2builder wraps the http://itextpdf.com[iText library] (version 2.x).
kamura-xssfbuilder wraps the https://poi.apache.org/[Apache POI library].

The modules are listed below. More details can be found in each module's own README.

* link:kamura-gdata-sheetreader/README.adoc[kamura-gdata-sheetreader]: Reader for Google Sheets
* link:kamura-hssfbuilder/README.adoc[kamura-hssfbuilder]: Builder for Microsoft Office XLS workbooks
* link:kamura-itext2builder/README.adoc[kamura-itext2builder]: Builder for PDF documents using iText2
* link:kamura-itext5builder/README.adoc[kamura-itext5builder]: Builder for PDF documents using iText5
* link:kamura-xssfbuilder/README.adoc[kamura-xssfbuilder]: Builder for Microsoft Office XLSX (Office 2007) workbooks
* link:kamura-zip4jbuilder/README.adoc[kamura-zip4jbuilder]: Builder for ZIP streams using http://www.lingala.net/zip4j/[Zip4j]
* link:kamura-zipbuilder/README.adoc[kamura-zipbuilder]: Builder for ZIP streams using JDK ZIP support

There are a few other modules in the project too, providing tools and demonstration programs.
